[package]
name = "spde"
version = "0.1.0"
edition = "2021"
description = "SPDE Super‑Download‑Engine 统一下载中心，单点CLI版本"
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
uuid = { version = "1.10", features = ["v4", "serde"] }
ctrlc = "3.4"
thiserror = "1.0"
anyhow = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "time", "fs", "io-util"] }
futures-util = "0.3.34"
# 0.13 正确feature：rustls、stream、system-proxy、socks
reqwest = { version = "0.13.4", features = ["rustls", "stream", "system-proxy", "socks"] }
url = "2.5.8"
async-trait = "0.1.92"
chrono = { version = "0.4", features = ["serde"] }





[lib]
crate-type = ["lib"]

[[bin]]
name = "spde"
path = "src/bin/main.rs"
